**Одинична матриця**

Одинична матриця — це квадратна матриця, у якої на головній діагоналі стоять одиниці, а всі інші елементи дорівнюють нулю. Одиничну матрицю позначають як I.

Для створення одиничної матриці можна використати метод *identity*, але є альтернативний варіант, метод *eye*, який при цьому дозволяє задати зміщення діагоналі з одиничними значеннями. Зміщення задаємо через ключ значення k :

In [1]:
import numpy as np

a = np.eye(4, k=-1, dtype=float)
print(a)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


**Обернена матриця**

Bизначаємо обернену матрицю - ми можемо помножити на обернене число, тобто число в -1 степені. 
Обернена матриця існує лише для квадратної матриці — матриці, у якої к-сть рядків рівна к-сті стовпців.

Для отримання оберненої матриці необхідно використати функцію *inv* із пакету *linalg*.

In [2]:
import numpy as np

a = np.array([[ 1, 0, 3],
              [-1,-1, 2],
              [ 4, 7, 2]])

a_inv = np.linalg.inv(a)
print(a_inv)

[[ 0.64 -0.84 -0.12]
 [-0.4   0.4   0.2 ]
 [ 0.12  0.28  0.04]]
