<a href="https://colab.research.google.com/github/YuliiaChorna1/DS-01.1-Linear-Algebra/blob/main/matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Матриці**

Оскільки ndarray є масивом, то створивши масив масивів, ми отримаємо матрицю:

In [1]:
import numpy as np
m = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)

print(m)

[[1 2 3]
 [4 5 6]]


Розмірність матриці, як і векторів, можна подивитись за допомогою даного атрибуту shape:

In [2]:
import numpy as np

a = np.array([1, 2, 3, 4, 5], dtype=float)
print(a.shape)  # (5,)

m = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)
print(m.shape)  # (2, 3)

(5,)
(2, 3)


Операції з матрицями будуть відбуватися таким самим чином, як і з вектором, оскільки це у нас масив масивів, окрім множення.

Якщо ми будемо використовувати оператор ∗ , то отримаємо поелементне множення всіх відповідних елементів двох матриць і можливо провести таку операцію *лише для двох матриць однієї розмірності* :

In [3]:
import numpy as np

a = np.array([[2, 3, 4, 5],
              [1, 2, 3, 4]])

b = np.array([[2, 2, 2, 2],
              [1, 1, 1, 1]])

print(a*b)

[[ 4  6  8 10]
 [ 1  2  3  4]]


**Множення матриць**

Множення матриць — це алгебраїчна операція, яка використовується для обчислення нової матриці шляхом множення двох вихідних матриць. Якщо ми маємо дві матриці A та B, де A має розмірність m×n (тобто має
m рядків і n стовпців), а B має розмірність n×p (має n рядків і p стовпців), то їх добуток AB буде матрицею C розмірності m×p, де кожен елемент нової матриці c обчислюється як скалярний добуток i-ого рядка матриці A та j-ого стовпця матриці B​.

Дану операцію можна провести лише у випадку, коли рядки матриці A мають такий же розмір, як і стовпці матриці B, тобто к-сть стовпців матриці A повинна бути рівна к-сті рядків матриці B.

In [4]:
import numpy as np

a = np.array([[1, 2, 3],
              [0, 1, 2]])

b = np.array([[ 1, 2],
              [ 0, 4],
              [-1, 0]])

c = np.dot(a, b)
print(c)

[[-2 10]
 [-2  4]]


**Транспонування та зміна форми матриць в numpy**

​Транспонування матриці — заміна рядків матриці на її стовпці, а стовпців, на рядки:

In [6]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(a)
b = a.T
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


Розмірність вектора або матриці можна також змінювати методом *reshape*

In [7]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = a.reshape((3, 2))
print(b)

[[1 2]
 [3 4]
 [5 6]]


Перетворення матриці в плоский вектор за допомогою методу *flatten*:

In [8]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.flatten()
print(b)

[1 2 3 4 5 6]
