### можливості NumPy

атрибути масиву ndarray:

*shape* - розмір масиву вздовж кожної з його осей, повертається як кортеж цілих чисел

*ndim* - кількість осей. зверніть увагу: ndim == len(shape)

*size* - загальна кількість елементів у масиві, рівна добутку кортежу shape

*dtype* - тип даних масиву

*data* - "буфер" в памяті, що містить дійсні елементи масиву

*itemsize* - розмір у байтах кожного елемента

Створити вектор або матрицю, які складаються з одиниць:

In [1]:
import numpy as np

a = np.ones((5,), dtype=float)
print(a)

m = np.ones((2, 3), dtype=int)
print(m)

[1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]]


Cтворити вектор або матрицю, які складаються з нулів:

In [2]:
import numpy as np

a = np.zeros(5, dtype=float)
print(a)

m = np.zeros((2, 3), dtype=int)
print(m)

[0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]]


Cтворення масиву, що містить послідовність чисел (np.arange & np.linspace):

Метод *np.arange* (аналогічний методу range in Python) - не включає останні елементи послідовності:

In [3]:
import numpy as np

a = np.arange(5)
b = np.arange(1, 3, 0.5)
print(a)
print(b)

[0 1 2 3 4]
[1.  1.5 2.  2.5]


Метод *np.linspace* - включає останній елемент визначеної послідовності.
ключовий параметр num визначає кількість елементів у послідовності:

In [6]:
import numpy as np

a = np.linspace(1, 5, num=5)
b = np.linspace(1, 3, num=3)
print(a)
print(b)

[1. 2. 3. 4. 5.]
[1. 2. 3.]


Cтворювати масиви та матриці наповнені випадковими значеннями:

In [7]:
import numpy as np
a = np.random.random(3)
b = np.random.random((3, 3))
print(a)
print(b)

[0.88536462 0.42264446 0.08706637]
[[0.66744048 0.9222229  0.75530536]
 [0.64758625 0.46860386 0.0617628 ]
 [0.80467458 0.4806908  0.48376547]]


## Індексація

Масив NumPy можна розділити на частини та присвоїти їм індекси. Принцип роботи схожий на те, як це відбувається зі списками Python.

In [8]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a[0])
print(a[1:])
print(a[:2])

1
[2 3 4 5]
[1 2]


Індексація багатовимірного масиву NumPy:

In [9]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[1, 1])
print(a[1:, 1])
print(a[0, :2])

5
[5 8]
[1 2]
